### ISSUE TITLE
N/A data

### ISSUE THREAD

**Issue by jainish-wify** [rekit/antd-form-builder#120]
Hi there,

I dont want to show all the N/A data in viewmode, please help me how to do that.

Thanks in advance.

**Comment by supnate** [comment]
you can provide `renderView` method to render anything you like.

**Comment by jainish-wify** [comment]
@supnate Thank you for your time. 

Basically I have 10 Data rendering in viewmode but 5/10 data is N/A and i dont want to show those data.

Thanks in advance.

**Comment by supnate** [comment]
If you don't want to show some fields you can construct the meta based on your data.
