### ISSUE TITLE
form validate the field which is not exist after I remove it

### ISSUE THREAD

**Issue by nttdocomo** [rekit/antd-form-builder#13]
https://codesandbox.io/embed/frosty-dawn-5ntyc?fontsize=14&hidenavigation=1&theme=dark

this demo is modified base on the https://rekit.github.io/antd-form-builder/#dynamic-fields. I add a remove button at the bottom, when i cehck the other, the Other input field is show, but when i check orange or apple, the input is remove, but when i submit, the form validate is got an error

**Comment by supnate** [comment]
I can't see the code. Please paste it here.

**Comment by nttdocomo** [comment]
> I can't see the code. Please paste it here.

I have update the link

**Comment by supnate** [comment]
Yes, this is by design. Because in wizard, we don't want to set preserve to true for every field.

**Comment by supnate** [comment]
Maybe we need to revisit this design. Sorry for the confusion.

**Comment by supnate** [comment]
Added highlighted notes for the difference of default value of `preserve` and `validateFirst`, rather than changing the API.

**Comment by supnate** [comment]
Final update: the `preserve` and `validateFirst` default value is changed to `false` to be consistent with antd. Just released in `1.1.0`.
