### ISSUE TITLE
Migration to the new Form Api in the antd v4?

### ISSUE THREAD

**Issue by gino8080** [rekit/antd-form-builder#17]
Are there any projects to upgrade this lib for the new Ant v4 Form APi?
 
https://next.ant.design/components/form/v3

https://next.ant.design/components/form/

**Comment by supnate** [comment]
Will do it when antd v4 formal released if necessary.

**Comment by blueandhack** [comment]
When I upgrade antd to 4.0 RC, I meet with the error
```
./node_modules/antd-form-builder/dist/index.es.js
Attempted import error: 'Icon' is not exported from 'antd'.
```

**Comment by supnate** [comment]
Thanks @blueandhack for reporting it. It's because `Icon` has be moved to `@ant-design/icons` in v4. I will address the issues after the v4 formal release.

**Comment by blueandhack** [comment]
@supnate Antd 4.0 release now.

https://github.com/ant-design/ant-design/issues/21656

Hopefully, antd-form-builder will compatibility soon.

**Comment by supnate** [comment]
Got it, thanks for the prompt reminding! @blueandhack

**Comment by JaLe29** [comment]
Hi guys, 

I have everything ready to PR, but I can't push my branch.

Give me a correct rights and I will create PR.

**Comment by supnate** [comment]
@JaLe29  Really? 😍 Creating PR doesn't need special permission.

**Comment by JaLe29** [comment]
@supnate 
hahaha, my bad. You are right!

CheckIt, CRIt, MergeIt.

Hope everything is OK according to standards in your repo.

**Comment by blueandhack** [comment]
> @JaLe29 Really? 😍 Creating PR doesn't need special permission.

Hi, I notice you updated antd-form-builder for version 4.0 in the master branch, but I have a question, does it compatibility for 3.0 version or it has breaking changes?

**Comment by supnate** [comment]
@blueandhack Yes, it will be compatible for both 4.x and 3.x.

**Comment by blueandhack** [comment]
> @blueandhack Yes, it will be compatible for both 4.x and 3.x.

I just wondering know when it will be bumping a new version?  Thank your repo!  🙏

**Comment by supnate** [comment]
Should be in this weekend.

**Comment by blueandhack** [comment]
@supnate May I donate the project with Paypal, Alipay or WeChat if you can publish QR Code.

**Comment by supnate** [comment]
Released just now and thanks @blueandhack for the kind suggestion! Maybe later:-)

**Comment by supnate** [comment]
You can find example usage at https://rekit.github.io/antd-form-builder/examples-v4/
