### ISSUE TITLE
Tabs support

### ISSUE THREAD

**Issue by jonathanroze** [rekit/antd-form-builder#22]
Hi, 

I just discover you package and it seems to be very helpful ! It's exactly what I'm looking for ! 

I saw we can set Wizard form and it's very fine, and I think i will be a great idea to support Tabs too ! 

Thanks for your work !

**Comment by supnate** [comment]
Thanks @jonathanroze , wizard is just a sample usage of FormBuilder but not because it supports wizard. Similarly, you can already use it in a Tab component.

**Comment by EssamEid614** [comment]
@jonathanroze 1 year late but I achieved this using a map over the fields to display multiple `FormBuilder` instances all with the same `form` prop and different meta.
