### ISSUE TITLE
InitialValues not working anymore

### ISSUE THREAD

**Issue by jonathanroze** [rekit/antd-form-builder#32]
HI,

I just switch from Antd@3 to Antd@4 and i upgrade your module.

I change my code to fit new specs but when I provide initialValues, there are not more informations in my fields.

**Comment by jonathanroze** [comment]
```
              <Form onSubmit={this.handleSubmit}>
                <FormBuilder form={this.form} meta={{...formLayout, initialValues: resource, disabled}} />
              </Form>
```

That my code, and resource object is in my component state, it's async loading (fetch from api)

**Comment by supnate** [comment]
I can't reproduce it. Could you create an example on codesandbox.io to reproduce?

**Comment by jonathanroze** [comment]
https://codesandbox.io/s/clever-wing-ggn5b?file=/src/App.js

**Comment by supnate** [comment]
In your case you modified initial value after form's rendering. This behavior has been changed for the antd's form API: https://ant.design/components/form/v3 . 

> In v3, modifying the initialValue of un-operated field will update the field value synchronously, which is a bug. However, since it has been used as a feature for a long time, we have not fixed it. In v4, the bug has been fixed. initialValues only takes effect when initializing and resetting the form.

The antd-form-builder just inherits the same behavior. So, to change field value after the initial rendering, you should use `this.form.setFieldValue(..)`.

**Comment by jonathanroze** [comment]
Ok perfect, thanks :)
