### ISSUE TITLE
'itemRef is not a function' with Antd version 4.4.0

### ISSUE THREAD

**Issue by blueandhack** [rekit/antd-form-builder#43]
When I upgrade Antd 4.4.0
I face error when I using Class Component

It shows the error
```
TypeError
itemRef is not a function
```

I think the problem with `FormBuilder.createForm(this)`

Reproduce
[![Edit ancient-bush-us7it](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-bush-us7it?fontsize=14&hidenavigation=1&theme=dark)

**Comment by supnate** [comment]
Thanks for reporting this and thanks for becoming the backer!! 😍

I will look into the issue since it's related with the latest Antd.

**Comment by supnate** [comment]
Fixed with v2.1.0 . It took a bit long time because it's big change. FormBuilder APIs are also changed incompatibly. And all antd form's private APIs were removed from form builder to ensure the stability when antd upgrades. You can see the examples for the new usage.
