### ISSUE TITLE
demo Custom Component not working

### ISSUE THREAD

**Issue by lemarcgagnon** [rekit/antd-form-builder#45]
Hello, in your demo, (https://rekit.github.io/antd-form-builder/examples-v4/#custom-component)

for the Custom Component... in the "Price" field... the value will not stay as it disappears the minute we leave the field.. could you please attend to it..  Also the filed keeps rendering in the console, could we use memo to limit this call?

Yours,

Marc

**Comment by supnate** [comment]
Fixed.
