### ISSUE TITLE
希望大佬支持下typescript

### ISSUE THREAD

**Issue by ghostjzf** [rekit/antd-form-builder#57]

**Comment by pig800509** [comment]
+1

**Comment by supnate** [comment]
Could you help to contribute the definition file?

**Comment by ghostjzf** [comment]
> Could you help to contribute the definition file?

你是想让我在你这里package.json增加types，根目录增加个index.d.ts这么支持吗？还是@types/antd-form-builder? 还是重构的你的代码变为tsx

**Comment by supnate** [comment]
index.d.ts 就可以了

**Comment by bermann** [comment]
Any news on this? Maybe I can help

**Comment by supnate** [comment]
> Any news on this? Maybe I can help

Yes, please, welcome for the help!

**Comment by supnate** [comment]
Thanks @wilds for the fix! The new version was just published.
